name: Testar

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Instalar Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "nix-rust"

    - name: Executar testes (Build e Run)
      run: nix develop -c cargo run --verbose

    - name: Upload servidor.log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: servidor-log
        path: testes/servidor.log
