name: Testar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build no Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: cargo build --verbose

      - name: Cache do Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Executar testes no Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: cargo run --verbose

      - name: Upload servidor.log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: servidor-log
          path: testes/servidor.log

      - name: Upload capturas de tela em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: telas
          path: testes/telas/
